import { InputFile } from 'grammy';
import type { Context } from 'grammy';
import { runAgentLoop } from '../agent/loop.js';
import { config } from '../config.js';

// ─── Text Message Handler ────────────────────────────────────────────────────
// Receives text messages from authorized users, runs the agent loop, replies.

export async function handleTextMessage(ctx: Context): Promise<void> {
    const text = ctx.message?.text;
    if (!text) return;

    console.log(`💬 Text from ${ctx.from?.first_name}: "${text.slice(0, 80)}${text.length > 80 ? '...' : ''}"`);

    // Show typing indicator while processing
    await ctx.replyWithChatAction('typing');

    try {
        const userId = ctx.from?.id;
        if (!userId) return;

        const result = await runAgentLoop(userId, text);

        if (result.toolsUsed.length > 0) {
            console.log(`  Used tools: ${result.toolsUsed.join(', ')} (${result.iterations} iterations)`);
        }

        // Split long messages (Telegram limit: 4096 chars)
        const maxLen = 4096;
        if (result.reply.length <= maxLen) {
            await ctx.reply(result.reply, { parse_mode: 'Markdown' }).catch(() =>
                ctx.reply(result.reply) // fallback without markdown if parsing fails
            );
        } else {
            for (let i = 0; i < result.reply.length; i += maxLen) {
                const chunk = result.reply.slice(i, i + maxLen);
                await ctx.reply(chunk, { parse_mode: 'Markdown' }).catch(() => ctx.reply(chunk));
            }
        }

        // Send any files generated by tools
        if (result.files && result.files.length > 0) {
            for (const file of result.files) {
                try {
                    if (file.type === 'photo') {
                        await ctx.replyWithPhoto(new InputFile(file.path), { caption: file.caption });
                    } else if (file.type === 'document') {
                        await ctx.replyWithDocument(new InputFile(file.path), { caption: file.caption });
                    } else if (file.type === 'voice') {
                        await ctx.replyWithVoice(new InputFile(file.path));
                    }
                } catch (fileErr) {
                    console.error(`  Failed to send file: ${file.path}`, fileErr);
                }
            }
        }
    } catch (err) {
        console.error('Agent loop error:', err);
        await ctx.reply('Sorry, something went wrong. Please try again.');
    }
}
